services:

  mysql:
    image: mysql:8.3
    container_name: mysql_gestionqr
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: restaurante_qr
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  backend:
    build: .
    container_name: backend_gestionqr
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"

  frontend:
    build: ../frontend
    container_name: frontend_gestionqr
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data: