export const traducciones = {
  es: {
    // General
    "guardar": "Guardar",
    "cancelar": "Cancelar",
    "editar": "Editar",
    "salir": "Salir",
    "cerrarSesion": "Cerrar sesión",
    "cargando": "Cargando...",
    "footer.avisoLegal": "Aviso legal",
    "footer.privacidad": "Política de privacidad",
    "footer.cookies": "Política de cookies",
    // Nav
    "nav.inicio": "Inicio",
    "nav.estadisticas": "Estadísticas",
    "nav.productos": "Productos",
    "nav.empleados": "Empleados",
    "nav.carta": "Carta",
    "nav.pedidos": "Pedidos",
    "nav.cocina": "Cocina",
    "nav.configuracion": "Configuración",
    "nav.cambiarContrasena": "Cambiar contraseña",
    // Inicio
    "inicio.bienvenido": "Bienvenido",
    "inicio.pedidosHoy": "Pedidos hoy",
    "inicio.ingresosHoy": "Ingresos hoy",
    "inicio.pendientesAhora": "Pendientes ahora",
    "inicio.listosParaServir": "Listos para servir",
    "inicio.estadisticas": "Estadísticas",
    "inicio.verMetricas": "Ver métricas detalladas",
    "inicio.productos": "Productos",
    "inicio.gestionarProductos": "Gestionar productos",
    "inicio.carta": "Carta",
    "inicio.gestionarPlatos": "Gestionar platos",
    "inicio.pedidos": "Pedidos",
    "inicio.verTodosPedidos": "Ver todos los pedidos",
    "inicio.empleados": "Empleados",
    "inicio.gestionarEmpleados": "Gestionar empleados",
    "inicio.irAPedidos": "Ir a Pedidos",
    "inicio.verPedidosMesa": "Ver pedidos por mesa",
    "inicio.enCocina": "En cocina",
    "inicio.totalActivos": "Total activos",
    "inicio.pedidosEsperando": "Pedidos esperando",
    "inicio.enPreparacion": "En preparación",
    "inicio.listos": "Listos",
    "inicio.irACocina": "Ir a Cocina",
    "inicio.gestionarPedidos": "Gestionar pedidos",
    // Estadísticas
    "stats.titulo": "Estadísticas",
    "stats.ingresosHoy": "Ingresos hoy",
    "stats.ingresosAyer": "Ingresos ayer",
    "stats.pedidosHoy": "Pedidos hoy",
    "stats.pedidosAyer": "Pedidos ayer",
    "stats.vsAyer": "vs ayer",
    "stats.platosMasVendidos": "Platos más vendidos",
    "stats.ingresosSemana": "Ingresos últimos 7 días",
    "stats.sinDatos": "Sin datos aún",
    "stats.cargando": "Cargando estadísticas...",
    "stats.novedosos": "Novedades con mejor aceptación",
    "stats.afluencia": "Afluencia por franja horaria",
    "stats.diasSemana": "Días con más pedidos",
    "stats.tramoMasVentas": "Tramo con más ventas",
    "stats.diasQueMasSeVende": "Días que más se vende",
    "stats.seHaPedido": "Se ha pedido",
    "stats.veces": "veces",
    "stats.introducidoHace": "Introducido hace",
    "stats.dias": "días",
    "stats.periodo30d": "30 días",
    "stats.periodo2m": "2 meses",
    "stats.periodo3m": "3 meses",
    "stats.periodo6m": "6 meses",
    "stats.periodo1y": "1 año",
    "stats.desayuno": "Desayuno",
    "stats.comida": "Comida",
    "stats.cena": "Cena",
    "stats.lunes": "Lunes",
    "stats.martes": "Martes",
    "stats.miercoles": "Miércoles",
    "stats.jueves": "Jueves",
    "stats.viernes": "Viernes",
    "stats.sabado": "Sábado",
    "stats.domingo": "Domingo",
    // Carta
    "carta.titulo": "Platos y Bebidas",
    "carta.buscar": "Buscar plato...",
    "carta.todosTipos": "Todos los tipos",
    "carta.primero": "Primero",
    "carta.segundo": "Segundo",
    "carta.tercero": "Tercero",
    "carta.postre": "Postre",
    "carta.bebida": "Bebida",
    "carta.seleccionarTipo": "Seleccionar tipo",
    "plato.nombreEs": "Nombre del plato...",
    "plato.nombreEn": "Dish name in English (optional)...",
    "plato.descripcionEs": "Descripción del plato...",
    "plato.descripcionEn": "Dish description in English (optional)...",
    "plato.imagen": "Imagen",
    "plato.vistaPrevia": "Vista previa",
    "carta.añadirPlato": "+ Añadir plato",
    "carta.plato": "Plato",
    "carta.descripcion": "Descripción",
    "carta.tipo": "Tipo",
    "carta.disponible": "Disponible",
    "carta.precio": "Precio",
    "carta.acciones": "Acciones",
    "carta.mostrando": "Mostrando",
    "carta.platos": "platos",
    // Carta — tabs y editor
    "carta.tabPlatos": "Platos y Bebidas",
    "carta.tabCartas": "Cartas",
    "carta.tabMenus": "Menús",
    "carta.tabQRs": "Códigos QRs",
    "carta.proximamente": "Próximamente...",
    "carta.editarPlato": "Editar plato",
    "carta.crearPlato": "Crear nuevo plato",
    "carta.eliminarPlato": "Eliminar plato",
    "carta.eliminarCarta": "Eliminar carta",
    "carta.confirmarEliminar": "Se eliminará",
    "carta.crearNuevaCarta": "+ Crear nueva carta",
    "carta.nombreCarta": "Nombre de la carta...",
    "carta.buscarCarta": "Buscar...",
    "carta.sinCartas": "No hay cartas. Crea una nueva.",
    "carta.sinBanner": "Sin imagen de portada",
    "carta.cambiarImagen": "Cambiar imagen",
    "carta.añadirSeccion": "+ Añadir sección",
    "carta.eliminarSeccion": "Eliminar sección",
    "carta.añadirPlatoSeccion": "Añadir plato a esta sección",
    "carta.seleccionarPlato": "Seleccionar plato",
    "carta.seccionVacia": "Esta sección está vacía",
    "carta.nombreSeccion": "Nombre de la sección...",
    "carta.nombreSeccionEn": "Nombre en inglés (opcional)...",
    "carta.eliminar": "Eliminar",
    "carta.novedad": "Novedad",
    "carta.novedadNoBebida": "No aplicable a bebidas",
    // QR
    "carta.codigoQR": "Código QR",
    "carta.mesa": "Mesa",
    "carta.descargarQR": "Descargar QR",
    "carta.imprimirCarta": "Imprimir carta con QR",
    "carta.textoQR": "Este QR permite a los clientes ver la carta, pedir y pagar desde sus móviles sin registrarse ni logearse",
    //Camarero
    "cartaCamarero.mensajeSeleccionMesa": "Selecciona el número de mesa para acceder.",
    "cartaCamarero.seleccionarMesa": "Seleccionar Mesa",
    // Empleados
    "empleados.titulo": "Empleados",
    "empleados.anadir": "Añadir empleado",
    "empleados.añadir": "Añadir empleado",
    "empleados.editar": "Editar empleado",
    "empleados.actualizar": "Actualizar",
    "empleados.cancelar": "Cancelar",
    "empleados.nombre": "Nombre...",
    "empleados.email": "Email...",
    "empleados.contrasena": "Contraseña...",
    "empleados.seleccionarRol": "Seleccionar rol",
    "empleados.seleccionarEstado": "Seleccionar estado",
    "empleados.buscar": "Buscar empleado...",
    "empleados.todosRoles": "Todos los roles",
    "empleados.todosEstados": "Todos los estados",
    "empleados.camarero": "Camarero",
    "empleados.cocinero": "Cocinero",
    "empleados.gerente": "Gerente",
    "empleados.activo": "Activo",
    "empleados.descanso": "Descanso",
    "empleados.vacaciones": "Vacaciones",
    "empleados.eliminar": "Eliminar empleado",
    "empleados.columnaEmpleado": "Empleado",
    "empleados.columnaRol": "Rol",
    "empleados.columnaEstado": "Estado",
    "empleados.toastAnadido": "Empleado añadido correctamente",
    "empleados.toastAñadido": "Empleado añadido correctamente",
    "empleados.toastEditado": "Empleado actualizado correctamente",
    // Pedidos
    "pedidos.titulo": "Gestión de Pedidos",
    "pedidos.pendientes": "Pendientes",
    "pedidos.enProceso": "En proceso",
    "pedidos.listos": "Listos",
    "pedidos.servido": "Servido",
    "pedidos.estadoPendiente": "Pendiente",
    "pedidos.estadoListo": "Listo",
    "pedidos.mesa": "Mesa",
    "pedidos.iniciarPreparacion": "Iniciar preparación",
    "pedidos.marcarListo": "Marcar como listo",
    "pedidos.marcarServido": "Marcar como servido",
    // Cocina
    "cocina.titulo": "Cocina",
    "cocina.sinPendientes": "Sin pedidos pendientes",
    "cocina.sinEnProceso": "Sin pedidos en proceso",
    "cocina.iniciarPreparacion": "Iniciar preparación",
    "cocina.marcarListo": "Marcar como listo",
    // Camarero
    "camarero.titulo": "Pedidos",
    "camarero.listosParaServir": "Listos para servir",
    "camarero.enCocina": "En cocina",
    "camarero.sinListos": "No hay pedidos listos",
    "camarero.marcarServido": "Marcar como servido",
    "camarero.mesa": "Mesa",
    "camarero.sinEnCocina": "Sin pedidos en cocina",
    "camarero.mesasParaCerrar": "Mesas para cerrar",
    "camarero.sinMesasParaCerrar": "No hay mesas pendientes de cierre",
    "camarero.cerrarMesa": "Cerrar mesa",
    "camarero.cerrarMesaTitle": "Cerrar mesa y liberar sesión QR",
    "camarero.pedidosServidos": "pedidos servidos",
    // Configuración
    "config.titulo": "Configuración",
    "config.infoRestaurante": "Información del restaurante",
    "config.nombreRestaurante": "Nombre del restaurante",
    "config.telefono": "Teléfono de contacto",
    "config.direccion": "Dirección del establecimiento",
    "config.emailContacto": "Email de contacto",
    "config.logo": "Logo",
    "config.cambiarLogo": "Cambiar logo",
    "config.sinLogo": "Sin logo",
    "config.idiomaCartaTitulo": "Idioma de la carta",
    "config.español": "Español",
    "config.ingles": "Inglés",
    "config.clientePuedeCambiar": "El cliente podrá cambiar el idioma desde la carta digital",
    "config.personalizacionVisual": "Personalización visual",
    "config.aplicaACarta": "(aplica a la carta digital del cliente)",
    "config.colorPrimario": "Color primario",
    "config.colorSecundario": "Color secundario",
    "config.imagenFondo": "Imagen de fondo (carta digital del cliente)",
    "config.cambiarFondo": "Cambiar imagen de fondo",
    "config.guardado": "Configuración guardada correctamente",
    "config.error": "Error al guardar la configuración",
    "config.guardando": "Guardando...",
    "config.placeholderNombre": "Nombre...",
    "config.placeholderTelefono": "Tfno...",
    "config.placeholderDireccion": "Dirección...",
    "config.placeholderEmail": "Email...",
    "config.vistaPrevia": "Vista previa:",
    "config.colorPrimarioLabel": "Primario",
    "config.colorSecundarioLabel": "Secundario",
    "config.guardarCambios": "Guardar cambios",
    // Contraseña
    "contrasena.titulo": "Cambiar contraseña",
    "contrasena.actual": "Contraseña actual",
    "contrasena.nueva": "Nueva contraseña",
    "contrasena.confirmar": "Confirmar nueva contraseña",
    "contrasena.guardar": "Guardar contraseña",
    "contrasena.noCoinciden": "Las contraseñas nuevas no coinciden",
    "contrasena.muyCorta": "La contraseña debe tener al menos 4 caracteres",
    "contrasena.actualizada": "Contraseña actualizada correctamente",
    "contrasena.incorrecta": "La contraseña actual no es correcta",
    "contrasena.error": "Error al cambiar la contraseña",
    // Login
    "login.titulo": "Iniciar sesión",
    "login.subtitulo": "Panel de gestión",
    "login.email": "Correo electrónico",
    "login.contrasena": "Contraseña",
    "login.boton": "Entrar",
    "login.error": "Credenciales incorrectas",
    // Menú del día
    "menu.titulo": "Menús",
    "menu.precioMenu": "Precio del menú...",
    "menu.seleccionarDia": "Seleccionar día",
    "menu.crearNuevoMenu": "Crear nuevo menú",
    "menu.añadirPlatoPrimerosMenu": "Añadir primero al menú",
    "menu.añadirPlatoSegundosMenu": "Añadir segundo al menú",
    "menu.añadirPlatoPostresMenu": "Añadir postre al menú",
    "menu.añadirPlatoBebidasMenu": "Añadir bebida al menú",
    "menu.nombreMenu": "Nombre del menú...",
    "menu.seleccionarPlato": "Buscar menú...",
    "menu.buscarMenu": "Buscar menú",
    "menu.menuVacio": "El menú está vacío",
    "menu.eliminarMenu": "Eliminar menú",
    "menu.confirmarEliminar": "Se eliminará",
    "menu.cancelar": "Cancelar",
    "menu.guardar": "Guardar",
    "menu.primeros": "Primeros",
    "menu.segundos": "Segundos",
    "menu.postres": "Postres",
    "menu.bebidas": "Bebidas",
    "menu.noHayPrimeros": "No hay primeros disponibles",
    "menu.noHaySegundos": "No hay segundos disponibles",
    "menu.noHayBebidas": "No hay bebidas disponibles",
    "menu.noHayPostres": "No hay postres disponibles",
    "menu.sinMenus": "No hay menús. Crea uno nuevo.",
    "menu.sinImagen": "Sin imagen de portada",
    "menu.diaMenu": "Día del menú",
    "menu.diaLunes": "Lunes",
    "menu.diaMartes": "Martes",
    "menu.diaMiercoles": "Miércoles",
    "menu.diaJueves": "Jueves",
    "menu.diaViernes": "Viernes",
    "menu.diaSabado": "Sábado",
    "menu.diaDomingo": "Domingo",
    // Proveedores
    "proveedores.titulo": "Proveedores",
    "proveedores.anadir": "Añadir proveedor",
    "proveedores.añadir": "Añadir proveedor",
    "proveedores.editar": "Editar proveedor",
    "proveedores.actualizar": "Actualizar proveedor",
    "proveedores.cancelar": "Cancelar",
    "proveedores.nombre": "Nombre del proveedor...",
    "proveedores.email": "Email del proveedor...",
    "proveedores.telefono": "Teléfono del proveedor...",
    "proveedores.descripcion": "Descripción del proveedor...",
    "proveedores.telefono.placeholder": "Tfno...",
    "proveedores.email.placeholder": "Email...",
    "proveedores.buscar": "Buscar proveedor...",
    "proveedores.eliminar": "Eliminar proveedor",
    "proveedores.SeleccionarProveedor": "Seleccionar proveedor",
    "proveedores.añadirProveedor": "Añadir nuevo proveedor",
    "proveedores.editarProveedor": "Editar proveedor",
    "proveedores.crearProveedor": "Crear proveedor",
    "proveedores.seleccionarProveedor": "Seleccionar proveedor",
    // Productos
    "productos.titulo": "Productos",
    "productos.anadir": "Añadir producto",
    "productos.añadir": "Añadir producto",
    "productos.editar": "Editar producto",
    "productos.actualizar": "Actualizar producto",
    "productos.cancelar": "Cancelar",
    "productos.descripcion": "Descripción del producto...",
    "productos.mostrando": "Mostrando",
    "productos.productos": "productos",
    "productos.precio": "Precio del producto",
    "producto.prroveedor": "Proveedor",
    "productos.producto": "Producto",
    "productos.nombre": "Nombre del producto",
    "productos.stock": "Stock disponible",
    "productos.proveedor": "Proveedor",
    "productos.acciones": "Acciones",
    "productos.buscar": "Buscar producto...",
    "productos.eliminar": "Eliminar producto",
    "productos.eliminarProducto": "Eliminar producto",
    "productos.confirmarEliminar": "Se eliminará",
    "productos.seleccionar.proveedor": "Seleccionar proveedor",
    "producto.descripcion": "Descripción del producto...",
    "productos.añadirProducto": "Añadir nuevo producto",
    "productos.editarProducto": "Editar producto",
    "productos.añadirProveedor": "Añadir nuevo proveedor",
  },
  en: {
    // General
    "guardar": "Save",
    "cancelar": "Cancel",
    "editar": "Edit",
    "salir": "Log out",
    "cerrarSesion": "Log out",
    "cargando": "Loading...",
    "footer.avisoLegal": "Legal notice",
    "footer.privacidad": "Privacy policy",
    "footer.cookies": "Cookie policy",
    // Nav
    "nav.inicio": "Home",
    "nav.estadisticas": "Statistics",
    "nav.productos": "Products",
    "nav.empleados": "Employees",
    "nav.carta": "Menu",
    "nav.pedidos": "Orders",
    "nav.cocina": "Kitchen",
    "nav.configuracion": "Settings",
    "nav.cambiarContrasena": "Change password",
    // Inicio
    "inicio.bienvenido": "Welcome",
    "inicio.pedidosHoy": "Orders today",
    "inicio.ingresosHoy": "Revenue today",
    "inicio.pendientesAhora": "Pending now",
    "inicio.listosParaServir": "Ready to serve",
    "inicio.estadisticas": "Statistics",
    "inicio.verMetricas": "View detailed metrics",
    "inicio.productos": "Products",
    "inicio.gestionarProductos": "Manage products",
    "inicio.carta": "Menu",
    "inicio.gestionarPlatos": "Manage dishes",
    "inicio.pedidos": "Orders",
    "inicio.verTodosPedidos": "View all orders",
    "inicio.empleados": "Staff",
    "inicio.gestionarEmpleados": "Manage staff",
    "inicio.irAPedidos": "Go to Orders",
    "inicio.verPedidosMesa": "View orders by table",
    "inicio.enCocina": "In kitchen",
    "inicio.totalActivos": "Total active",
    "inicio.pedidosEsperando": "Orders waiting",
    "inicio.enPreparacion": "In preparation",
    "inicio.listos": "Ready",
    "inicio.irACocina": "Go to Kitchen",
    "inicio.gestionarPedidos": "Manage orders",
    // Statistics
    "stats.titulo": "Statistics",
    "stats.ingresosHoy": "Revenue today",
    "stats.ingresosAyer": "Revenue yesterday",
    "stats.pedidosHoy": "Orders today",
    "stats.pedidosAyer": "Orders yesterday",
    "stats.vsAyer": "vs yesterday",
    "stats.platosMasVendidos": "Best selling dishes",
    "stats.ingresosSemana": "Revenue last 7 days",
    "stats.sinDatos": "No data yet",
    "stats.cargando": "Loading statistics...",
    "stats.novedosos": "New dishes acceptance",
    "stats.afluencia": "Traffic by time slot",
    "stats.diasSemana": "Busiest days",
    "stats.tramoMasVentas": "Top time slot",
    "stats.diasQueMasSeVende": "Best selling days",
    "stats.seHaPedido": "Ordered",
    "stats.veces": "times",
    "stats.introducidoHace": "Introduced",
    "stats.dias": "days ago",
    "stats.periodo30d": "30 days",
    "stats.periodo2m": "2 months",
    "stats.periodo3m": "3 months",
    "stats.periodo6m": "6 months",
    "stats.periodo1y": "1 year",
    "stats.desayuno": "Breakfast",
    "stats.comida": "Lunch",
    "stats.cena": "Dinner",
    "stats.lunes": "Monday",
    "stats.martes": "Tuesday",
    "stats.miercoles": "Wednesday",
    "stats.jueves": "Thursday",
    "stats.viernes": "Friday",
    "stats.sabado": "Saturday",
    "stats.domingo": "Sunday",
    // Menu
    "carta.titulo": "Dishes & Drinks",
    "carta.buscar": "Search dish...",
    "carta.todosTipos": "All types",
    "carta.primero": "Starter",
    "carta.segundo": "Main course",
    "carta.tercero": "Third course",
    "carta.postre": "Dessert",
    "carta.bebida": "Drink",
    "carta.seleccionarTipo": "Select type",
    "plato.nombreEs": "Dish name in Spanish...",
    "plato.nombreEn": "Dish name (optional)...",
    "plato.descripcionEs": "Description in Spanish...",
    "plato.descripcionEn": "Description (optional)...",
    "plato.imagen": "Image",
    "plato.vistaPrevia": "Preview",
    "carta.añadirPlato": "+ Add dish",
    "carta.plato": "Dish",
    "carta.descripcion": "Description",
    "carta.tipo": "Type",
    "carta.disponible": "Available",
    "carta.precio": "Price",
    "carta.acciones": "Actions",
    "carta.mostrando": "Showing",
    "carta.platos": "dishes",
    // Menu — tabs and editor
    "carta.tabPlatos": "Dishes & Drinks",
    "carta.tabCartas": "Menus",
    "carta.tabMenus": "Set Menus",
    "carta.tabQRs": "QR Codes",
    "carta.proximamente": "Coming soon...",
    "carta.editarPlato": "Edit dish",
    "carta.crearPlato": "Create new dish",
    "carta.eliminarPlato": "Delete dish",
    "carta.eliminarCarta": "Delete menu",
    "carta.confirmarEliminar": "Will be deleted",
    "carta.crearNuevaCarta": "+ Create new menu",
    "carta.nombreCarta": "Menu name...",
    "carta.buscarCarta": "Search...",
    "carta.sinCartas": "No menus. Create one.",
    "carta.sinBanner": "No cover image",
    "carta.cambiarImagen": "Change image",
    "carta.añadirSeccion": "+ Add section",
    "carta.eliminarSeccion": "Delete section",
    "carta.añadirPlatoSeccion": "Add dish to this section",
    "carta.seleccionarPlato": "Select dish",
    "carta.seccionVacia": "This section is empty",
    "carta.nombreSeccion": "Section name...",
    "carta.nombreSeccionEn": "Name in English (optional)...",
    "carta.eliminar": "Delete",
    "carta.novedad": "New",
    "carta.novedadNoBebida": "Not applicable to drinks",
    //CAMARERO
    "cartaCamarero.mensajeSeleccionMesa": "Select table number to access.",
    "cartaCamarero.seleccionarMesa": "Select Table",
    // Suppliers
    "proveedores.titulo": "Suppliers",
    "proveedores.anadir": "Add supplier",
    "proveedores.añadir": "Add supplier",
    "proveedores.editar": "Edit supplier",
    "proveedores.actualizar": "Update supplier",
    "proveedores.cancelar": "Cancel",
    "proveedores.nombre": "Supplier name...",
    "proveedores.email": "Supplier email...",
    "proveedores.telefono": "Supplier phone...",
    "proveedores.descripcion": "Supplier description...",
    "proveedores.telefono.placeholder": "Phone...",
    "proveedores.email.placeholder": "Email...",
    "proveedores.buscar": "Search supplier...",
    "proveedores.eliminar": "Delete supplier",
    "proveedores.SeleccionarProveedor": "Select supplier",
    "proveedores.añadirProveedor": "Add new supplier",
    "proveedores.editarProveedor": "Edit supplier",
    "proveedores.crearProveedor": "Add supplier",
    "proveedores.seleccionarProveedor": "Select supplier",
    // Products
    "productos.titulo": "Products",
    "productos.anadir": "Add product",
    "productos.añadir": "Add product",
    "productos.editar": "Edit product",
    "productos.actualizar": "Update product",
    "productos.cancelar": "Cancel",
    "productos.descripcion": "Product description...",
    "productos.mostrando": "Showing",
    "productos.productos": "products",
    "productos.precio": "Product price",
    "producto.prroveedor": "Supplier",
    "productos.producto": "Product",
    "productos.nombre": "Product name",
    "productos.stock": "Stock",
    "productos.proveedor": "Supplier",
    "productos.acciones": "Actions",
    "productos.buscar": "Search product...",
    "productos.eliminar": "Delete product",
    "productos.eliminarProducto": "Delete product",
    "productos.confirmarEliminar": "Will be deleted",
    "productos.seleccionar.proveedor": "Select supplier",
    "producto.descripcion": "Product description...",
    "productos.añadirProducto": "Add new product",
    "productos.editarProducto": "Edit product",
    "productos.añadirProveedor": "Add new supplier",
    // QR
    "carta.codigoQR": "QR Code",
    "carta.mesa": "Table",
    "carta.descargarQR": "Download QR",
    "carta.imprimirCarta": "Print menu with QR",
    "carta.textoQR": "This QR allows customers to view the menu, order and pay from their phones without registering",
    // Employees
    "empleados.titulo": "Employees",
    "empleados.anadir": "Add employee",
    "empleados.añadir": "Add employee",
    "empleados.editar": "Edit employee",
    "empleados.actualizar": "Update",
    "empleados.cancelar": "Cancel",
    "empleados.nombre": "Name...",
    "empleados.email": "Email...",
    "empleados.contrasena": "Password...",
    "empleados.seleccionarRol": "Select role",
    "empleados.seleccionarEstado": "Select status",
    "empleados.buscar": "Search employee...",
    "empleados.todosRoles": "All roles",
    "empleados.todosEstados": "All statuses",
    "empleados.camarero": "Waiter",
    "empleados.cocinero": "Chef",
    "empleados.gerente": "Manager",
    "empleados.activo": "Active",
    "empleados.descanso": "Break",
    "empleados.vacaciones": "Vacation",
    "empleados.eliminar": "Delete employee",
    "empleados.columnaEmpleado": "Employee",
    "empleados.columnaRol": "Role",
    "empleados.columnaEstado": "Status",
    "empleados.toastAnadido": "Employee added successfully",
    "empleados.toastAñadido": "Employee added successfully",
    "empleados.toastEditado": "Employee updated successfully",
    "pedidos.titulo": "Order Management",
    "pedidos.pendientes": "Pending",
    "pedidos.enProceso": "In progress",
    "pedidos.listos": "Ready",
    "pedidos.servido": "Served",
    "pedidos.estadoPendiente": "Pending",
    "pedidos.estadoListo": "Ready",
    "pedidos.mesa": "Table",
    "pedidos.iniciarPreparacion": "Start preparation",
    "pedidos.marcarListo": "Mark as ready",
    "pedidos.marcarServido": "Mark as served",
    // Kitchen
    "cocina.titulo": "Kitchen",
    "cocina.sinPendientes": "No pending orders",
    "cocina.sinEnProceso": "No orders in progress",
    "cocina.iniciarPreparacion": "Start preparation",
    "cocina.marcarListo": "Mark as ready",
    // Waiter
    "camarero.titulo": "Orders",
    "camarero.listosParaServir": "Ready to serve",
    "camarero.enCocina": "In kitchen",
    "camarero.sinListos": "No orders ready",
    "camarero.marcarServido": "Mark as served",
    "camarero.mesa": "Table",
    "camarero.sinEnCocina": "No orders in kitchen",
    "camarero.mesasParaCerrar": "Tables to close",
    "camarero.sinMesasParaCerrar": "No tables pending closure",
    "camarero.cerrarMesa": "Close table",
    "camarero.cerrarMesaTitle": "Close table and release QR session",
    "camarero.pedidosServidos": "served orders",
    // Settings
    "config.titulo": "Settings",
    "config.infoRestaurante": "Restaurant information",
    "config.nombreRestaurante": "Restaurant name",
    "config.telefono": "Contact phone",
    "config.direccion": "Establishment address",
    "config.emailContacto": "Contact email",
    "config.logo": "Logo",
    "config.cambiarLogo": "Change logo",
    "config.sinLogo": "No logo",
    "config.idiomaCartaTitulo": "Menu language",
    "config.español": "Spanish",
    "config.ingles": "English",
    "config.clientePuedeCambiar": "The customer can change the language from the digital menu",
    "config.personalizacionVisual": "Visual customization",
    "config.aplicaACarta": "(applies to the customer's digital menu)",
    "config.colorPrimario": "Primary color",
    "config.colorSecundario": "Secondary color",
    "config.imagenFondo": "Background image (customer's digital menu)",
    "config.cambiarFondo": "Change background image",
    "config.guardado": "Settings saved successfully",
    "config.error": "Error saving settings",
    "config.guardando": "Saving...",
    "config.placeholderNombre": "Name...",
    "config.placeholderTelefono": "Phone...",
    "config.placeholderDireccion": "Address...",
    "config.placeholderEmail": "Email...",
    "config.vistaPrevia": "Preview:",
    "config.colorPrimarioLabel": "Primary",
    "config.colorSecundarioLabel": "Secondary",
    "config.guardarCambios": "Save changes",
    // Password
    "contrasena.titulo": "Change password",
    "contrasena.actual": "Current password",
    "contrasena.nueva": "New password",
    "contrasena.confirmar": "Confirm new password",
    "contrasena.guardar": "Save password",
    "contrasena.noCoinciden": "New passwords do not match",
    "contrasena.muyCorta": "Password must be at least 4 characters",
    "contrasena.actualizada": "Password updated successfully",
    "contrasena.incorrecta": "Current password is incorrect",
    "contrasena.error": "Error changing password",
    // Login
    "login.titulo": "Sign in",
    "login.subtitulo": "Management panel",
    "login.email": "Email address",
    "login.contrasena": "Password",
    "login.boton": "Sign in",
    "login.error": "Incorrect credentials",
    // Daily menu
    "menu.titulo": "Menus",
    "menu.precioMenu": "Menu price...",
    "menu.seleccionarDia": "Select day",
    "menu.crearNuevoMenu": "Create new menu",
    "menu.añadirPlatoPrimerosMenu": "Add starter to menu",
    "menu.añadirPlatoSegundosMenu": "Add main course to menu",
    "menu.añadirPlatoPostresMenu": "Add dessert to menu",
    "menu.añadirPlatoBebidasMenu": "Add drink to menu",
    "menu.nombreMenu": "Menu name...",
    "menu.seleccionarPlato": "Select dish",
    "menu.buscarMenu": "Search menu...",
    "menu.menuVacio": "Menu is empty",
    "menu.eliminarMenu": "Delete menu",
    "menu.confirmarEliminar": "Will be deleted",
    "menu.cancelar": "Cancel",
    "menu.guardar": "Save",
    "menu.primeros": "Starters",
    "menu.segundos": "Main courses",
    "menu.postres": "Desserts",
    "menu.bebidas": "Drinks",
    "menu.noHayPrimeros": "No starters available",
    "menu.noHaySegundos": "No main courses available",
    "menu.noHayBebidas": "No drinks available",
    "menu.noHayPostres": "No desserts available",
    "menu.sinMenus": "No menus. Create one.",
    "menu.sinImagen": "No cover image",
    "menu.diaMenu": "Menu day",
    "menu.diaLunes": "Monday",
    "menu.diaMartes": "Tuesday",
    "menu.diaMiercoles": "Wednesday",
    "menu.diaJueves": "Thursday",
    "menu.diaViernes": "Friday",
    "menu.diaSabado": "Saturday",
    "menu.diaDomingo": "Sunday",
  }
};
